name: Trigger Runtime Builds

on:
  workflow_run:
    workflows: [Snapshots]
    types: [completed]
    branches:
      - "development"
  workflow_dispatch: # Allow manual triggering

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Trigger Workflow for boxlang-miniserver Repo
        run: |
          # Set the required variables
          target_repo_owner="ortus-boxlang"
          target_repo_name="boxlang-miniserver"
          target_branch="development"
          bx_version="1.0.0"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT_BOXLANG }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$target_repo_owner/$target_repo_name/actions/workflows/snapshot.yml/dispatches \
            -d "{\"ref\": \"$target_branch\", \"inputs\": {\"version\": \"$bx_version\"}}"

      - name: Trigger Workflow for boxlang-servlet Repo
        run: |
          # Set the required variables
          target_repo_owner="ortus-boxlang"
          target_repo_name="boxlang-servlet"
          target_branch="development"
          bx_version="1.0.0"

          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHA_WORKFLOW_DISPATCHER_PAT_BOXLANG }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$target_repo_owner/$target_repo_name/actions/workflows/snapshot.yml/dispatches \
            -d "{\"ref\": \"$target_branch\", \"inputs\": {\"version\": \"$bx_version\"}}"
